name: Build main

on:
  push:
    branches:
    - main

jobs:
  trigger:
    name: trigger
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with: 
          node-version: 18.12.0

      - name: install dependencies
        run: |
          npm install
          ls
          pwd

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Build
        run: npm run build

      - name: Deploy
        uses: Azure/webapps-deploy@v3.0.0
        with:
          app-name: 'currency-front'
          package: './src/App.tsx'
