
name: Build main

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Repository branch or tag'
        required: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!
